vim.keymap.set("n", "<leader>,", [[:w<cr>]], { silent = true, desc = "Save" })
vim.keymap.set("n", "<leader>.", [[:noh<cr>]], { silent = true, desc = "Remove search highlights" })
vim.keymap.set("n", "<leader>x", [[:bd<cr>]], { silent = true, desc = "Save" })
vim.keymap.set("n", "<leader>c", [[:close<cr>]], { silent = true, desc = "Save" })
vim.keymap.set("n", "<leader>q", [[:q<cr>]], { silent = true, desc = "Save" })
vim.keymap.set("n", "<leader>e", vim.diagnostic.open_float, { desc = "Open floating diagnostic message" })
